package com.neurosys.backend.enums;

public enum AlertType {
    CPU_SUSTAINED_HIGH,
    MEMORY_PRESSURE,
    DISK_SPACE_LOW,
    DISK_SPACE_CRITICAL,
    ENDPOINT_OFFLINE,
    TELEMETRY_STALE,
    HIGH_CPU,
    HIGH_RAM,
    HIGH_DISK,
    LOW_FREE_DISK,
    OFFLINE,
    HIGH_TEMP,
    NETWORK_DOWN,
    NETWORK_DISCONNECTED,
    NO_INTERNET,
    THRESHOLD,
    ANOMALY,
    AI_PREDICTION,
    HIGH_RISK
}
