# NeuroSys Monitoring Agent Configuration
server.url=https://realtimesystemmonitoring-production-7322.up.railway.app/api/v1
agent.lab.name=Computer Lab 3
agent.collection.interval.seconds=1
agent.cache.dir=./cache
